### ISSUE TITLE
The Elder Scrolls 4: Oblivion - Crash on start

### ISSUE THREAD

**Issue by XJDHDR** [disks86/VK9#58]
VK9 v0.27.0
Windows 10 Pro x64 1703
Nvidia GeForce 1080 Ti with v398.82 drivers

I'm sorry if this bug report is inappropriate at this time. I know that VK9 is still in early development and I highly appreciate what you are doing.
I tried to use VK9 with TES4: Oblivion but the game crashed on start. I have attached the log file that was created. The log is 190 KB and there was one section where the logger just inserted a large sequence of NULL characters.

[VK9.log](https://github.com/disks86/VK9/files/2331347/VK9.log)

**Comment by disks86** [comment]
Can you re-try this with the "0.28.1" release that I just pushed out?

**Comment by XJDHDR** [comment]
Just gave it a try. The game is still crashing on start. The main change I an seeing in the log is that a large number of "CheckDeviceFormat is not implemented" messages have been replaced by "CheckDeviceFormat (D3D_OK)" messages. I am seeing a few "CheckDeviceFormat (D3DERR_NOTAVAILABLE)" messages and I'm still getting that large block of NULL characters.

Here is the log file from v0.28.1:
[VK9.log](https://github.com/disks86/VK9/files/2453336/VK9.log)

**Comment by disks86** [comment]
Thank you for checking. At this point I'd probably need to run the game through PIX to see what kind of weird stuff it's doing. I don't own the game though. The deluxe edition is only like $20 on steam though so I might pick it later.

**Comment by XJDHDR** [comment]
Just want to clarify that I'm not rushing you to get this game supported. You can take as long as you want.
If you do decide to pick up this game, I would personally recommend rather buying it through GOG ( https://www.gog.com/game/elder_scrolls_iv_oblivion_game_of_the_year_edition_deluxe_the ). The game is the same price there as on Steam and you don't have to deal with Steam's DRM potentially causing issues. I would also recommend waiting for a sale as I have seen this game discounted at least 50% a few times this year. Otherwise, if you enjoy open-world fantasy RPGs, I would definitely recommend giving this game a try.

**Comment by disks86** [comment]
I ended up picking up the game. I haven't tested it yet though.
